export const Images = {
    logo: require('./images/logo.png'),
    toy1: require('./images/toy_face1.png'),
    toy2: require('./images/toy_face2.png'),
    user: require('./images/user.png'),
    email: require('./images/email.png'),
    calendar: require('./images/calendar.png'),
    home:require('./images/home.png'),
    heart:require('./images/heart.png'),
    orders: require('./images/orders.png'),
    homeUser: require('./images/homeUser.png'),
    active_home: require('./images/active_home.png'),
    active_heart:require('./images/active_heart.png'),
    active_orders:require('./images/active_orders.png'),
    active_user: require('./images/active_user.png'),
    ic_search: require('./images/search.png'),
    ic_food_1: require('./images/food_1.png'),
    ic_food_2:require('./images/food_2.png'),
    ic_food_3:require('./images/food_3.png'),
    ic_food_4: require('./images/food_4.png'),
    ic_order_bg: require('./images/ordersBg.png'),
    ic_user1: require('./images/User1.png'),
    ic_left_icon: require('./images/chevron-left.png'),
    ic_right_icon: require('./images/chevron-right.png'),
    ic_cart_white: require('./images/cart_white.png'),
    ic_swipe_text: require('./images/swipe_text.png'),
    ic_delete: require('./images/Trash.png'),
    ic_bank: require('./images/bank.png'),
    ic_card: require('./images/card.png'),
    ic_paypal: require('./images/paypal.png'),
    ic_check: require('./images/check.png'),
    ic_uncheck: require('./images/uncheck.png'),
    ic_success_gif:require('./images/successGif.gif')



}